module hpsfpga (
    // FPGA SIDE
    input  fpga_clk,
    output fpga_mosi,
    input  fpga_miso,
    output s0,
    output fpga_sck,

    // HPS SIDE
    inout  HPS_CONV_USB_N,
    output HPS_DDR3_ADDR,
    output HPS_DDR3_BA,
    output HPS_DDR3_CAS_N,
    output HPS_DDR3_CKE,
    output HPS_DDR3_CK_N,
    output HPS_DDR3_CK_P,
    output HPS_DDR3_CS_N,
    output HPS_DDR3_DM,
    inout  HPS_DDR3_DQ,
    inout  HPS_DDR3_DQS_N,
    inout  HPS_DDR3_DQS_P,
    output HPS_DDR3_ODT,
    output HPS_DDR3_RAS_N,
    output HPS_DDR3_RESET_N,
    input  HPS_DDR3_RZQ,
    output HPS_DDR3_WE_N,
    output HPS_ENET_GTX_CLK,
    inout  HPS_ENET_INT_N,
    output HPS_ENET_MDC,
    inout  HPS_ENET_MDIO,
    input  HPS_ENET_RX_CLK,
    input  HPS_ENET_RX_DATA,
    input  HPS_ENET_RX_DV,
    output HPS_ENET_TX_DATA,
    output HPS_ENET_TX_EN,
    inout  HPS_KEY,
    output HPS_SD_CLK,
    inout  HPS_SD_CMD,
    inout  HPS_SD_DATA,
    input  HPS_UART_RX,
    output HPS_UART_TX,
    input  HPS_USB_CLKOUT,
    inout  HPS_USB_DATA,
    input  HPS_USB_DIR,
    input  HPS_USB_NXT,
    output HPS_USB_STP,
);

endmodule
